/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scriptable_QuickJSConnector */

#ifndef _Included_org_scriptable_QuickJSConnector
#define _Included_org_scriptable_QuickJSConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scriptable_QuickJSConnector
 * Method:    nativeNewQJSRuntime
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_scriptable_QuickJSConnector_nativeNewQJSRuntime
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_scriptable_QuickJSConnector
 * Method:    nativeFreeQJSRuntime
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_scriptable_QuickJSConnector_nativeFreeQJSRuntime
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_scriptable_QuickJSConnector
 * Method:    nativeCallQJS
 * Signature: ([B[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_scriptable_QuickJSConnector_nativeCallQJS
  (JNIEnv *, jobject, jbyteArray, jobjectArray);

/*
 * Class:     org_scriptable_QuickJSConnector
 * Method:    nativeGetQJSException
 * Signature: ([B)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_scriptable_QuickJSConnector_nativeGetQJSException
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
